"base_title" = "跳轉樞紐 Redirection hub"
"base_tagline" = "位於墨玉程市的跳轉樞紐"
"base_description" = "Redirection hub in CuttleCity"
"base_url" = "https://xn--2os22eixx6na.xn--kpry57d/redirect"
"base_year" = "2020-2023"
"author_name" = "DJ Tratoh"
"author_url" = "https://sotong.cloud/@sotongdj"
"author_email" = "mail@stdj.me"
"open_preview" = "位於墨玉程市的跳轉樞紐 Redirection hub in CuttleCity"
"category_preview" = "Category: {}"
"paginate_number" = 5
"paginate_format" = ""
"separator_preview" = "<!--excerpt-->"
"read_more" = "more"
"read_original" = "original"
